<?php
echo "<pre>";
echo 'SERVER_NAME = ' . ($_SERVER['SERVER_NAME']);
echo "<br />";
echo 'HTTP_X_WAP_MSISDN = '. $_SERVER['HTTP_X_WAP_MSISDN'];
echo "<br />";
echo 'HTTP_IP = ' . ($_SERVER['HTTP_IP']);
echo "<br />";
echo 'X_WAP_MSISDN = ' . ($_SERVER['X_WAP_MSISDN']);
echo "<br />";
echo 'MSISDN = ' . ($_SERVER['MSISDN']);
echo "<br />";
echo 'HTTP-MSISDN = ' . ($_SERVER['HTTP-MSISDN']);
echo "<br />";
echo 'HTTP_MSISDN = ' . ($_SERVER['HTTP_MSISDN']);
echo "<br />";
echo 'msisdn = ' . ($_SERVER['msisdn']);
echo "<br />";
echo 'HTTP_X_UP_CALLING_LINE_ID = ' . ($_SERVER['HTTP_X_UP_CALLING_LINE_ID']);
echo "<br />";
echo 'HTTP_X_FORWARDED_FOR = ' . ($_SERVER['HTTP_X_FORWARDED_FOR']);
echo "<br />";
echo 'HTTP_X_UP_CALLING_LINE_ID = ' . ($_SERVER['HTTP_X_UP_CALLING_LINE_ID']);
echo "<br />";
echo 'HTTP_IF_MODIFIED_SINCE = ' . ($_SERVER['HTTP_IF_MODIFIED_SINCE']);
echo "<br />";
echo 'HTTP_X_OPERAMINI_PHONE_UA = ' . ($_SERVER['HTTP_X_OPERAMINI_PHONE_UA']);
echo "<br />";
echo 'X-WAP-3GPP-IMSI = ' . ($_SERVER['X-WAP-3GPP-IMSI']);
echo "<br />";
echo "</pre>";exit();